package sauthc1

import (
	"net/http"
	"time"
	"strconv"
	"math"
	"math/big"
	"crypto/rand"
	// "encoding/base64"
	"github.com/jmcvetta/guid"
	// "github.com/jmcvetta/randutil"
)

type ApiKey string

type Sauthc1Signer struct {
	DefaultAlgorithm     string
	HostHeader           string
	AuthorizationHeader  string
	StorpathDateHeader   string
	IdTerminator         string
	Algorithm            string
	AuthenticationScheme string
	Sauthc1Id            string
	Sauthc1SignedHeaders string
	Sauthc1Signature     string
	DateFormat           string
	TimestampFormat      string
	Newline              string
	GuidGenerator guid.Generator
}

// DefaultSigner returns a new Sauthc1Signer object initialized with the default
// values.
func DefaultSigner() Sauthc1Signer {
	s := Sauthc1Signer{
		DefaultAlgorithm:     "SHA256",
		HostHeader:           "Host",
		AuthorizationHeader:  "Authorization",
		StorpathDateHeader:   "X-Stormpath-Date",
		IdTerminator:         "sauthc1_request",
		Algorithm:            "HMAC-SHA-256",
		AuthenticationScheme: "SAuthc1",
		Sauthc1Id:            "sauthc1Id",
		Sauthc1SignedHeaders: "sauthc1SignedHeaders",
		Sauthc1Signature:     "sauthc1Signature",
		DateFormat:           "%Y%m%d",
		TimestampFormat:      "%Y%m%dT%H%M%SZ",
		Newline:              "\n",
		GuidGenerator: guid.SimpleGenerator(),
	}
	return s
}

// nonce returns concatenated string representations of a guid, generated by a
// snowflake algorithm, and a random integer.
//
// Note:  I have no fucking clue if this is a cryptographically secure nonce.  I
// think it might be, but you really shouldn't rely on that.
func (s *Sauthc1Signer) nonce() (string, error) {
	var result string
	// GUID
	i, err := s.GuidGenerator.NextId()
	if err != nil {
		return result, err
	}
	result = strconv.FormatInt(i, 10)
	// Random Int64
	b, err := rand.Int(rand.Reader, big.NewInt(math.MaxInt64))
	result += strconv.FormatInt(b.Int64(), 10)
	return result, nil // Success!
}

func (s *Sauthc1Signer) Sign(req *http.Request, key ApiKey) error {
	now := time.Now()
	timeStamp := now.Format(s.TimestampFormat)
	dateStamp := now.Format(s.DateFormat)
	nonce, err := s.nonce()
	if err != nil {
		return err
	}
	url := req.URL
	host := url.Host
	return nil // Success!
}
